AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HeatRiskAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Timeout: 900
      MemorySize: 3008
      Environment:
        Variables:
          BUCKET_NAME: local-test-bucket